const M = [
    ["Qora shakar tapioka choyi", 0, 40000, "🟤", "#e8c9a8", "A1"], ["Sutli choy", 0, 40000, "🧋", "#f3dcc4", "A3"], ["O'rikli sutli choy", 0, 40000, "🍑", "#ffd8c4", "A3"], ["Jasmin sutli choy", 0, 40000, "🌼", "#fff0c2", "A1"], ["Yashil choy limon", 0, 40000, "🍋", "#e3f0bf", "B3"], ["Qulupnayli chizmik", 0, 40000, "🍓", "#ffd0d8", "B4"], ["Uzumli sutli choy", 0, 40000, "🍇", "#e6d3f2", "C1"], ["Mango limon", 0, 40000, "🥭", "#ffe3a3", "C5"], ["Ananasli choy", 0, 40000, "🍍", "#fff0b0", "D3"], ["Uzumli kokos", 0, 40000, "🥥", "#eadcf2", "D3"],
    ["Mango choyi", 1, 34000, "🥭", "#ffe3a3", "A1"], ["Soya sutli choy", 1, 34000, "🥛", "#f3e8d6", "A2"], ["Pudingli sutli choy", 1, 34000, "🍮", "#ffe9b8", "A5"], ["Qizil loviyali sutli choy", 1, 34000, "🫘", "#f0d2c4", "A6"], ["Qora sutli choy", 1, 40000, "⚫", "#e2d5cc", "A7"], ["Jasmin sutli choy", 1, 40000, "🌼", "#fff0c2", "B2"],
    ["Mango choyi", 2, 40000, "🥭", "#ffe3a3", "B1"], ["Passion mevali choy", 2, 42000, "🍹", "#ffe0a0", "B5"], ["Limon choyi", 2, 40000, "🍋", "#fff3b0", "B6"], ["O'rmon mevali choy", 2, 40000, "🍓", "#ffc4c4", "B7"], ["Jasmin choyi", 2, 40000, "🌼", "#fff0c2", "B8"], ["Tog' choyi", 2, 40000, "🍃", "#d5e8bf", "B9"], ["Ko'k mevali choy", 2, 40000, "🫐", "#d8d4f2", "B10"], ["Muzli limon choyi", 2, 35000, "🧊", "#dff3df", "B11"],
    ["Kumquat limon", 3, 40000, "🍊", "#ffd9a8", "B12"], ["Jasmin yashil choy", 3, 40000, "🍵", "#d5e8bf", "B13"], ["Greyfurt limon", 3, 40000, "🍊", "#ffc9a8", "B14"], ["Passion mango", 3, 42000, "🥭", "#ffe3a3", "C3"], ["Mango ananas choyi", 3, 42000, "🍍", "#ffeaa8", "C4"], ["Mango limon kokos", 3, 42000, "🥥", "#fff0c2", "C6"], ["Passion uzum", 3, 42000, "🍇", "#e6d3f2", "C7"],
    ["Amerikano qahva", 4, 30000, "☕", "#e0cbb8", "D1"], ["Latte qahva", 4, 40000, "☕", "#f3dcc4", "D2"],
    ["Kokos yong'og'i", 5, 1000, "🥥", "#f4efe8", ""], ["Qizil loviya", 5, 1000, "🫘", "#f0d2c4", ""], ["Marvarid", 5, 1000, "⚪", "#e2d5cc", ""], ["Kui bo bo", 5, 1000, "🟡", "#fff0c2", ""], ["Puding", 5, 1000, "🍮", "#ffe9b8", ""]];
const CATS = [["Молочные чаи и тапиока", "Tapioka va sutli choylar"], ["Фруктовые чаи", "Mevali choylar"], ["Свежеприготовленные напитки", "Yangi tayyorlangan ichimliklar"], ["Кофе", "Qahva"], ["Добавки (топпинги)", "Masalliqlar (topping)"]], TOP = [33, 34, 35, 36, 37], HIT = [0, 1, 7, 5];
const ND = { uz: ["Qora shakar ta'mli choy, tapioka (boba) sharchalari bilan", "Klassik sutli choy", "O'rik ta'mli sutli choy", "Jasmin hidli sutli choy", "Yashil choy va limon", "Qulupnay ta'mli desert ichimlik", "Uzum ta'mli sutli choy", "Mango va limon ta'mli ichimlik", "Ananas ta'mli choy", "Uzum va kokos ta'mli ichimlik", "Mango ta'mli choy", "Soya suti bilan choy", "Puding qo'shilgan sutli choy", "Qizil loviya qo'shilgan sutli choy", "Qora choy va sut", "Jasmin choyi va sut", "Mango ta'mli choy, haqiqiy meva bilan", "Passion mevasi (marakuya) bilan choy, haqiqiy meva bilan", "Limonli choy, haqiqiy meva bilan", "O'rmon rezavorlari bilan choy, haqiqiy meva bilan", "Jasmin hidli choy, haqiqiy meva bilan", "Yashil rangli tog' choyi", "Ko'k rezavorlar bilan choy, haqiqiy meva bilan", "Sovuq limonli choy, muz bilan", "Kumquat (kichkina apelsinga o'xshash sitrus meva) va limon ichimligi", "Jasmin hidli yashil choy", "Greyfurt va limon ichimligi", "Passion mevasi va mango ichimligi", "Mango va ananas choyi", "Mango, limon va kokos ichimligi", "Passion mevasi va uzum ichimligi", "Sutsiz qora qahva (americano)", "Sutli qahva (latte)", "Kokos bo'laklari", "Shirin qizil loviya", "Tapioka sharchalari (marvarid)", "Qo'shimcha topping", "Yumshoq puding"], ru: ["Чай со вкусом чёрного сахара и шариками тапиоки", "Классический чай с молоком", "Молочный чай со вкусом абрикоса", "Молочный чай с ароматом жасмина", "Зелёный чай с лимоном", "Десертный напиток со вкусом клубники", "Молочный чай со вкусом винограда", "Напиток со вкусом манго и лимона", "Чай со вкусом ананаса", "Напиток со вкусом винограда и кокоса", "Чай со вкусом манго", "Чай с соевым молоком", "Молочный чай с пудингом", "Молочный чай с красной фасолью", "Чёрный чай с молоком", "Жасминовый чай с молоком", "Чай с манго и настоящими фруктами", "Чай с маракуйей и настоящими фруктами", "Лимонный чай с настоящими фруктами", "Чай с лесными ягодами и настоящими фруктами", "Жасминовый чай с настоящими фруктами", "Зелёный горный чай", "Чай с синими ягодами и настоящими фруктами", "Холодный лимонный чай со льдом", "Напиток с кумкватом (маленький цитрус, похож на мини-апельсин) и лимоном", "Зелёный чай с ароматом жасмина", "Напиток с грейпфрутом и лимоном", "Напиток с маракуйей и манго", "Чай с манго и ананасом", "Напиток с манго, лимоном и кокосом", "Напиток с маракуйей и виноградом", "Чёрный кофе без молока (американо)", "Кофе с молоком (латте)", "Кокосовая стружка", "Сладкая красная фасоль", "Шарики тапиоки (жемчужины)", "Дополнительный топпинг", "Нежный пудинг"] };
const NC = [0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4]; M.forEach((m, i) => m[1] = NC[i]);
const NR = ["Чай с тапиокой на чёрном сахаре", "Молочный чай", "Молочный чай с абрикосом", "Молочный жасминовый чай", "Зелёный чай с лимоном", "Клубничный чизкейк", "Молочный чай с виноградом", "Манго-лимон", "Ананасовый чай", "Виноград с кокосом", "Манговый чай", "Соевый молочный чай", "Молочный чай с пудингом", "Молочный чай с красной фасолью", "Чёрный молочный чай", "Молочный жасминовый чай", "Манговый чай", "Чай с маракуйей и фруктами", "Лимонный чай", "Лесной фруктовый чай", "Жасминовый чай", "Горный чай", "Чай с синими ягодами", "Ледяной лимонный чай", "Кумкват-лимон", "Зелёный жасминовый чай", "Грейпфрут-лимон", "Маракуйя-манго", "Манго-ананасовый чай", "Манго-лимон-кокос", "Маракуйя-виноград", "Кофе американо", "Кофе латте", "Кокосовая стружка", "Красная фасоль", "Жемчужины", "Куи бо бо", "Пудинг"];
const T = {
    ru: { mnote: "Цены в сумах. При заказе выберите сладость (0–100%) и топпинг (+1 000 сум).", n1: "Главная", n2: "Меню", n3: "О нас", n4: "Адреса", n5: "Контакты", h1: "Чай, который", h2: "обнимает", hp: "Свежий чай, натуральное молоко и мягкая тапиока — готовим прямо при вас.", b1: "Смотреть меню", b2: "Найти нас", why: "Почему нас любят", f1t: "Настоящий чай", f1d: "Заваренные листья, без порошков.", f2t: "Свежее молоко", f2d: "Мягкий сливочный вкус в каждом стакане.", f3t: "Ваша сладость", f3d: "Сахар от 0% до 100% — как вам нравится.", hits: "Хиты", bt: "Закажите онлайн", ab1: "7 Milk Tea — это любовь к тайваньскому чаю и уютные места, где приятно проводить время.", ab2: "Мы готовим каждый напиток свежим и подстраиваем его под ваш вкус.", city: "Ташкент", addr: "Открыть на карте", cp: "Вопросы, сотрудничество или заказ на праздник — напишите нам.", nm: "Имя", ph: "Телефон", msg: "Сообщение", send: "Отправить", cart: "Корзина", order: "Оформить заказ", thx: "Почти готово!", sugar: "Сахар", top: "Топпинг", add: "Добавить", cancel: "Отмена", search: "🔍 Найти напиток", fav: "Избранное", none: "Без топпинга", empty: "Корзина пуста — загляните в меню 🧋", sum: "Итого", nf: "Ничего не найдено", added: "Добавлено 🧋", need: "Укажите имя и телефон", cur: "сум", okm: "Спасибо, {n}! Заказ №{no} на {s}. Отправьте открывшееся сообщение в Telegram — мы подтвердим заказ." },
    uz: { mnote: "Narxlar so'mda. Buyurtmada shakar miqdori (0–100%) va topping (+1 000 so'm) tanlanadi.", n1: "Bosh sahifa", n2: "Menyu", n3: "Biz haqimizda", n4: "Manzillar", n5: "Aloqa", h1: "Sizni", h2: "quchoqlaydigan choy", hp: "Yangi choy, tabiiy sut va yumshoq tapioka — ko'z oldingizda tayyorlaymiz.", b1: "Menyuni ko'rish", b2: "Bizni toping", why: "Nega bizni yaxshi ko'rishadi", f1t: "Haqiqiy choy", f1d: "Damlangan barglar, kukunsiz.", f2t: "Yangi sut", f2d: "Har bir stakanda yumshoq qaymoqli ta'm.", f3t: "O'zingizga mos shirinlik", f3d: "Shakar 0% dan 100% gacha — o'zingiz tanlang.", hits: "Ommabop", bt: "Onlayn buyurtma bering", ab1: "7 Milk Tea — Tayvan choyiga muhabbat va vaqt o'tkazish yoqimli bo'lgan qulay joylar.", ab2: "Har bir ichimlikni yangi tayyorlaymiz va didingizga moslaymiz.", city: "Toshkent", addr: "Xaritada ochish", cp: "Savollar, hamkorlik yoki bayram buyurtmasi — bizga yozing.", nm: "Ism", ph: "Telefon", msg: "Xabar", send: "Yuborish", cart: "Savat", order: "Buyurtma berish", thx: "Deyarli tayyor!", sugar: "Shakar", top: "Topping", add: "Qo'shish", cancel: "Bekor qilish", search: "🔍 Ichimlik qidirish", fav: "Sevimlilar", none: "Toppingsiz", empty: "Savat bo'sh — menyuga qarang 🧋", sum: "Jami", nf: "Hech narsa topilmadi", added: "Qo'shildi 🧋", need: "Ism va telefonni kiriting", cur: "so'm", okm: "Rahmat, {n}! №{no} buyurtma ({s}). Telegramda ochilgan xabarni yuboring — buyurtmangizni tasdiqlaymiz." }
};
const $ = s => document.querySelector(s);
const ls = k => { try { return localStorage.getItem(k) } catch (e) { return null } }, sv = (k, v) => { try { localStorage.setItem(k, v) } catch (e) { } };
let lang = ls("sd_lang") == "ru" ? "ru" : "uz", cat = 0, qs = "", cart = {}, fav = [], oi = 0, lastTot = 0;
try { cart = JSON.parse(ls("sd_cart4") || "{}"); fav = JSON.parse(ls("sd_fav2") || "[]") } catch (e) { }
const t = k => T[lang][k], nm = i => lang == "ru" ? NR[i] : M[i][0], fmt = n => String(n).replace(/\B(?=(\d{3})+$)/g, " ") + " " + t("cur");
const toast = x => { const e = $("#toast"); e.textContent = x; e.classList.add("on"); setTimeout(() => e.classList.remove("on"), 2000) };
function sendTg(txt) { window.open("https://t.me/share/url?url=" + encodeURIComponent("7 Milk Tea") + "&text=" + encodeURIComponent(txt), "_blank") }
function go(p) { if (!document.getElementById(p)) p = "home"; document.querySelectorAll(".page").forEach(x => x.classList.toggle("on", x.id == p)); document.querySelectorAll("nav a").forEach(a => a.classList.toggle("on", a.dataset.go == p)); $("#nav").classList.remove("open"); scrollTo(0, 0); if (location.hash != "#" + p) history.replaceState(null, "", "#" + p) }
const CC = [["#fdaf4f", "#d8923c"], ["#ffddb5", "#ffe1b3"], ["#fff3cd", "#ffeec4"], ["#e9fb8b", "#eced7b"], ["#ebff62", "#d7f22e"], ["#ff5e55", "#fb4a44"], ["#e6a4e1", "#e49bd9"], ["#ffcf13", "#ffc316"], ["#ffe027", "#ffcf00"], ["#cf7ccd", "#f0d2f4"], ["#ffeec7", "#ffecc1"], ["#ffedc5", "#ffedc8"], ["#fff8d4", "#fff8ce"], ["#fff1c9", "#fff1cb"], ["#ffe7cb", "#ffe5c1"], ["#fbffc3", "#ecff7e"], ["#ffe72c", "#ffd82f"], ["#ffe456", "#fdcf1c"], ["#fff342", "#f5e500"], ["#ff2f2a", "#fd0b11"], ["#ffd727", "#ffcf1f"], ["#cdf31f", "#a9d417"], ["#b45fb3", "#bd47a9"], ["#e0fd72", "#caf518"], ["#ffbd0b", "#feb800"], ["#e6f838", "#c0da0d"], ["#ffdd52", "#ff8831"], ["#ffe159", "#ffcb00"], ["#ffd82f", "#ffc600"], ["#ffeb7d", "#ffc700"], ["#e378a8", "#ae217d"], ["#e96e14", "#753725"], ["#ffb140", "#fbf3e6"]], SP = [["pearl", 1, 0, 0], ["cream", 1, 0, 0], ["cream", 1, 0, 0], ["jelly", 1, 0, 0], ["none", 0, 1, 0], ["berry", 0, 1, 0], ["jelly", 0, 1, 0], ["none", 0, 1, 0], ["none", 0, 1, 0], ["none", 0, 1, 1], ["cream", 1, 0, 0], ["cream", 1, 0, 0], ["cream", 1, 0, 0], ["berry", 1, 0, 0], ["pearl", 1, 0, 0], ["jelly", 0, 0, 0], ["none", 0, 1, 0], ["cream", 0, 1, 0], ["lemon", 0, 1, 0], ["berry", 0, 1, 0], ["none", 0, 1, 0], ["jelly", 0, 1, 0], ["berry", 0, 1, 0], ["lemon", 0, 1, 0], ["none", 0, 1, 0], ["jelly", 0, 1, 0], ["none", 0, 1, 0], ["lemon", 0, 1, 0], ["none", 0, 1, 0], ["cream", 0, 1, 0], ["cream", 0, 1, 0], ["none", 0, 1, 0], ["foam", 0, 1, 1]];
const hx = h => [1, 3, 5].map(k => parseInt(h.slice(k, k + 2), 16)), mx = (a, b, t) => { const A = hx(a), B = hx(b); return "#" + A.map((v, k) => Math.round(v + (B[k] - v) * t).toString(16).padStart(2, "0")).join("") };
let cupN = 0;
function cupSvg(i, cl) {
    cl = cl || "cp"; const [c1, c2] = CC[i], [tp, bt, ic, ly] = SP[i], id = "c" + i + "_" + (++cupN); let o = "";
    const tcol = mx(c1, "#ffffff", .35), dark = mx(c1, "#000000", .35);
    o += `<svg class="${cl}" viewBox="0 0 120 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${M[i][0]}"><defs><linearGradient id="L${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${c1}"/>${ly ? `<stop offset=".55" stop-color="${c1}"/><stop offset=".78" stop-color="${c2}"/>` : ""}<stop offset="1" stop-color="${c2}"/></linearGradient><clipPath id="K${id}"><path d="M16 52H104L94 180Q93 190 84 190H36Q27 190 26 180Z"/></clipPath></defs>`;
    o += `<ellipse cx="60" cy="194" rx="36" ry="4.5" fill="rgba(70,35,10,.2)"/><rect x="64" y="0" width="7" height="140" rx="3.5" fill="#4b3a31" transform="rotate(7 67 70)"/>`;
    if (tp == "pearl") for (let r = 0; r < 2; r++)for (let k = 0; k < 6; k++)o += `<circle cx="${30 + k * 11 + r * 5}" cy="${44 - r * 7}" r="5.6" fill="#2b1a12"/><circle cx="${28.5 + k * 11 + r * 5}" cy="${42.2 - r * 7}" r="1.5" fill="#ffffff" opacity=".45"/>`;
    if (tp == "cream") o += `<ellipse cx="45" cy="42" rx="17" ry="10" fill="${mx(c1, "#ffffff", .65)}"/><ellipse cx="72" cy="40" rx="18" ry="11" fill="${mx(c1, "#ffffff", .55)}"/><ellipse cx="58" cy="35" rx="13" ry="8" fill="${mx(c1, "#ffffff", .75)}"/>`;
    if (tp == "jelly") for (let r = 0; r < 2; r++)for (let k = 0; k < 5; k++)o += `<rect x="${27 + k * 12 + r * 6}" y="${40 - r * 8}" width="10" height="10" rx="2.5" fill="${tcol}" stroke="${mx(c1, "#ffffff", .7)}" transform="rotate(${(k * 37 + r * 20) % 30 - 15} ${32 + k * 12 + r * 6} ${45 - r * 8})"/>`;
    if (tp == "berry") for (let r = 0; r < 2; r++)for (let k = 0; k < 6; k++)o += `<circle cx="${30 + k * 11 + r * 5}" cy="${44 - r * 7}" r="5" fill="${dark}"/><circle cx="${28.6 + k * 11 + r * 5}" cy="${42.5 - r * 7}" r="1.4" fill="#ffffff" opacity=".5"/>`;
    if (tp == "foam") o += `<ellipse cx="60" cy="46" rx="42" ry="9" fill="#fff6e6"/><ellipse cx="60" cy="42" rx="30" ry="7" fill="#fffaf0"/>`;
    o += `<path d="M14 54Q14 26 60 24Q106 26 106 54Z" fill="rgba(255,255,255,.3)" stroke="rgba(255,255,255,.85)" stroke-width="1.5"/>`;
    o += `<path d="M16 52H104L94 180Q93 190 84 190H36Q27 190 26 180Z" fill="url(#L${id})" fill-opacity=".97" stroke="rgba(255,255,255,.75)" stroke-width="1.5"/><g clip-path="url(#K${id})">`;
    if (ic) { [[22, 62, 14], [62, 58, -10], [80, 84, 20], [28, 90, -18], [72, 128, 10]].forEach(a => o += `<rect x="${a[0]}" y="${a[1]}" width="19" height="19" rx="4" fill="rgba(255,255,255,.3)" stroke="rgba(255,255,255,.65)" transform="rotate(${a[2]} ${a[0] + 9} ${a[1] + 9})"/>`) }
    if (bt) { [[32, 180], [43, 181], [54, 182], [65, 182], [76, 181], [87, 179], [38, 169], [49, 171], [60, 172], [71, 171], [82, 169], [44, 159], [56, 161], [68, 160], [79, 158]].forEach(p => o += `<circle cx="${p[0]}" cy="${p[1]}" r="5.4" fill="#2b1a12"/><circle cx="${p[0] - 1.5}" cy="${p[1] - 1.8}" r="1.4" fill="#ffffff" opacity=".4"/>`) }
    o += `<path d="M27 66L33 172" stroke="rgba(255,255,255,.4)" stroke-width="5" stroke-linecap="round"/><path d="M88 70L84 150" stroke="rgba(255,255,255,.18)" stroke-width="4" stroke-linecap="round"/></g>`;
    o += `<circle cx="60" cy="118" r="18" fill="#fffaf0" fill-opacity=".95" stroke="#9a6a48" stroke-width="2"/><text x="60" y="126" text-anchor="middle" font-family="Georgia,serif" font-weight="700" font-size="22" fill="#9a6a48">7</text>`;
    o += `<rect x="11" y="50" width="98" height="7" rx="3.5" fill="#ffffff" fill-opacity=".92" stroke="#e6d8c8"/>`;
    if (tp == "lemon") { o += `<ellipse cx="34" cy="30" rx="10" ry="5" fill="#5fae4e" transform="rotate(-25 34 30)"/><ellipse cx="46" cy="25" rx="9" ry="4.5" fill="#76c261" transform="rotate(10 46 25)"/><circle cx="94" cy="44" r="14" fill="#ffe36b" stroke="#fff3a8" stroke-width="2.5"/><g stroke="#fff3a8" stroke-width="1.6"><path d="M94 32V56M82 44H106M85.5 35.5L102.5 52.5M102.5 35.5L85.5 52.5"/></g>` }
    return o + "</svg>"
}
const pic = (i, c) => i < 33 ? cupSvg(i, c) : M[i][3];
function card(i) { const m = M[i]; return `<div class="card item"><div class="top" style="background:${m[4]}">${HIT.includes(i) ? '<span class="hit">🔥</span>' : ""}<button class="fav" data-fav="${i}">${fav.includes(i) ? "❤️" : "🤍"}</button>${pic(i, "cp")}</div><h3 style="font-size:1.1rem;margin:4px 0 0">${nm(i)}</h3><small class="desc">${ND[lang][i]}</small><div class="row"><span class="price">${fmt(m[2])}</span><button class="add" data-add="${i}" aria-label="+">+</button></div></div>` }
function drawMenu() { $("#tabs").innerHTML = CATS.map((c, j) => `<button class="${j == cat && !qs ? "on" : ""}" data-cat="${j}">${c[lang == "uz" ? 1 : 0]}</button>`).join("") + `<button class="${cat == 9 && !qs ? "on" : ""}" data-cat="9">❤️ ${t("fav")}</button>`; const L = M.map((m, i) => i).filter(i => qs ? nm(i).toLowerCase().includes(qs) : cat == 9 ? fav.includes(i) : M[i][1] == cat); $("#mg").innerHTML = L.map(card).join("") || `<p class="rev">${t("nf")}</p>` }
function apply() { document.documentElement.lang = lang; document.querySelectorAll("[data-t]").forEach(e => e.textContent = t(e.dataset.t)); document.querySelectorAll("[data-p]").forEach(e => e.placeholder = t(e.dataset.p)); $("#lg").textContent = lang == "ru" ? "UZ" : "RU"; $("#hits").innerHTML = HIT.map(card).join(""); drawMenu(); draw() }
const line = k => { const [a, su, tp] = k.split("|"), i = +a; return { i, pr: M[i][2] + (tp ? M[+tp][2] : 0), d: su ? `${t("sugar")} ${su}${tp ? " · + " + nm(+tp) : ""}` : "" } };
function draw() {
    let n = 0, s = 0, h = ""; for (const k in cart) { if (!M[+k.split("|")[0]]) { delete cart[k]; continue } const l = line(k); n += cart[k]; s += cart[k] * l.pr; h += `<div class="ln"><span style="font-size:1.8rem">${pic(l.i, "ci")}</span><span class="n">${nm(l.i)}<br><small class="desc">${l.d}</small><small class="price">${fmt(l.pr)}</small></span><span class="q"><button data-q="${k},-1">−</button> ${cart[k]} <button data-q="${k},1">+</button></span></div>` }
    sv("sd_cart4", JSON.stringify(cart)); lastTot = s; $("#cn").textContent = n; $("#lines").innerHTML = h || `<p class="rev">${t("empty")}</p>`; $("#sum").innerHTML = `<div class="row" style="padding-bottom:10px"><b>${t("sum")}</b><b class="price">${fmt(s)}</b></div>`
}
const oprice = () => M[oi][2] + ($("#otp").value ? M[+$("#otp").value][2] : 0), upO = () => $("#opr").textContent = fmt(oprice());
function openO(i) { oi = i; $("#ot").textContent = nm(i); $("#osu").value = "100%"; $("#otp").innerHTML = `<option value="">${t("none")}</option>` + TOP.map(x => `<option value="${x}">${nm(x)} (+${fmt(M[x][2])})</option>`).join(""); $("#opt").classList.add("open"); upO() }
document.addEventListener("click", e => {
    const T_ = e.target, g = T_.closest("[data-go]"), a = T_.closest("[data-add]"), c = T_.closest("[data-cat]"), q = T_.closest("[data-q]"), f = T_.closest("[data-fav]");
    if (g) go(g.dataset.go);
    if (a) { const i = +a.dataset.add; if (M[i][1] == 4) { const k = i + "||"; cart[k] = (cart[k] || 0) + 1; draw(); toast(t("added")) } else openO(i) }
    if (c) { cat = +c.dataset.cat; qs = ""; $("#q").value = ""; drawMenu() }
    if (f) { const i = +f.dataset.fav; fav = fav.includes(i) ? fav.filter(x => x != i) : [...fav, i]; sv("sd_fav2", JSON.stringify(fav)); apply() }
    if (q) { const p = q.dataset.q.split(","), k = p[0]; cart[k] = (cart[k] || 0) + +p[1]; if (cart[k] <= 0) delete cart[k]; draw() }
});
$("#otp").onchange = upO;
$("#oadd").onclick = () => { const k = [oi, $("#osu").value, $("#otp").value].join("|"); cart[k] = (cart[k] || 0) + 1; $("#opt").classList.remove("open"); draw(); toast(t("added")) };
$("#ox").onclick = () => $("#opt").classList.remove("open");
$("#q").oninput = e => { qs = e.target.value.trim().toLowerCase(); drawMenu() };
$("#lg").onclick = () => { lang = lang == "ru" ? "uz" : "ru"; sv("sd_lang", lang); apply() };
const openD = () => { $("#drawer").classList.add("open"); $("#ov").classList.add("open") }, closeD = () => { $("#drawer").classList.remove("open"); $("#ov").classList.remove("open") };
$("#cb").onclick = openD; $("#cc").onclick = closeD; $("#ov").onclick = closeD; $("#okb").onclick = () => $("#ok").classList.remove("open");
addEventListener("keydown", e => { if (e.key == "Escape") { closeD(); $("#ok").classList.remove("open"); $("#opt").classList.remove("open") } });
$("#ord").onclick = () => {
    if (!Object.keys(cart).length) return toast(t("empty")); const n = $("#oname").value.trim(), p = $("#ophone").value.trim(); if (!n || p.replace(/\D/g, "").length < 7) return toast(t("need"));
    const no = Math.floor(1000 + Math.random() * 9000), sl = lang; lang = "uz";
    let txt = `🧋 Yangi buyurtma №${no}\n👤 ${n}\n📞 ${p}\n\n`; for (const k in cart) { const l = line(k); txt += `• ${nm(l.i)}${l.d ? " (" + l.d + ")" : ""} × ${cart[k]} = ${fmt(cart[k] * l.pr)}\n` } txt += `\n💰 ${t("sum")}: ${fmt(lastTot)}`; lang = sl;
    $("#okt").textContent = t("okm").replace("{n}", n).replace("{no}", no).replace("{s}", fmt(lastTot));
    cart = {}; draw(); closeD(); $("#ok").classList.add("open"); sendTg(txt)
};
$("#send").onclick = () => { const n = $("#cname").value.trim(), p = $("#cph").value.trim(), m = $("#cmsg").value.trim(); if (!n || !p) return toast(t("need")); sendTg(`💬 ${n}\n📞 ${p}\n\n${m}`);["#cname", "#cph", "#cmsg"].forEach(s => $(s).value = "") };
$("#bg").onclick = () => $("#nav").classList.toggle("open");
$("#th").onclick = () => { const r = document.documentElement, d = r.dataset.theme == "dark" || (!r.dataset.theme && matchMedia("(prefers-color-scheme:dark)").matches); r.dataset.theme = d ? "light" : "dark" };
addEventListener("hashchange", () => go(location.hash.slice(1)));
apply(); go(location.hash.slice(1) || "home");
function sendTg(txt) {
    window.open("https://t.me/ProfdeFrancais6116?text=" + encodeURIComponent(txt), "_blank");
}